use Mix.Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# ContentoWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :contento, ContentoWeb.Endpoint,
  load_from_system_env: true,
  url: [scheme: "https", host: "contento-test.herokuapp.com", port: 443],
  force_ssl: [rewrite_on: [:x_forwarded_proto]],
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Configure Bamboo
config :contento, Contento.Mailer,
  adapter: Bamboo.SMTPAdapter

# Configure Endpoint
config :contento, ContentoWeb.Endpoint,
  secret_key_base: System.get_env("SECRET_KEY_BASE")

# Configure Database
config :contento, Contento.Repo,
  adapter: Ecto.Adapters.Postgres,
  url: System.get_env("DATABASE_URL"),
  pool_size: String.to_integer(System.get_env("POOL_SIZE") || "10"),
  ssl: true

# Configure Guardian
config :contento, Contento.Guardian,
  issuer: "contento_test_dev",
  secret_key: "b2hPQOSG+nKiK8iFoa/eVjIe4hhbi2wnz/oC6kzdEZd8MYzDpyD8xZReuIKmLtkg"

# Configure Bamboo
config :contento, Contento.Mailer,
  adapter: Bamboo.SMTPAdapter,
  server: {:system, "SMTP_SERVER"},
  port: {:system, "SMTP_PORT"},
  username: {:system, "SMTP_USERNAME"},
  password: {:system, "SMTP_PASSWORD"},
  tls: :if_available, # can be `:always` or `:never`
  allowed_tls_versions: [:"tlsv1", :"tlsv1.1", :"tlsv1.2"],
  ssl: false, # can be `true`
  retries: 1

import_config "prod.secret.exs"
